<Project>
  <PropertyGroup>
    <ParadiseVersion>0.46.0</ParadiseVersion>
    <Version>$(ParadiseVersion)</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ShouldUnsetParentConfigurationAndPlatform>false</ShouldUnsetParentConfigurationAndPlatform>
  </PropertyGroup>
</Project>
