<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Paradise.BT" />
    <PackageReference Include="Paradise.BT.Builder" />
    <PackageReference Include="Paradise.BT.Nodes" />

    <!-- Runtime packages include their source generators. -->
    <PackageReference Include="Paradise.ECS" />
  </ItemGroup>

</Project>
